### ISSUE TITLE
v0.5.0 Release Candidate 

### ISSUE THREAD

**Issue by brh55** [brh55/react-native-masonry#88]
**Current Release:** v0.5.0-alpha.1
## Tasks
- [x] Add priority arrangement (#5)
- [x] Fix duplicated images  (#81, #41, #61)
- [x] Add Lazy Loading (#87)
- [ ] Finish testing
- [ ] Update documentation
## Bugs
Please post any bugs and issues on here

**Comment by ahmedjamshed** [comment]
Duplicate image issue has been resolved in v0.5.0, but other two issues still persist. Although, single column render issue is not consistent on ios but it is consistent on android. I am attaching an image as a reference. Is there any quick fix for this? and the second issue is left biased render as you can see in ios simulator. 

<img width="698" alt="41281508-6c53a854-6de6-11e8-9a50-0ba9bac4e9c8" src="https://user-images.githubusercontent.com/23229626/41307291-9fd76c50-6e2d-11e8-9c23-54f882da8f8d.png">

**Comment by brh55** [comment]
@ahmedjamshed what are other to issues exactly?

**Comment by ahmedjamshed** [comment]
Issues still persist are 
1) left biased rendering as you can see on ios simulator
2) Single column rendering on Android and sometimes on ios as well, when images are cached

**Comment by brh55** [comment]
1. Left bias is default behavior, it will load based on what is resolved first. But with v0.5.0, not documented yet, you can use priority='balance', and it will do best effort to balance columns based on current state.

**Comment by brh55** [comment]
2. Not entirely sure, I haven't done any testing on android. I would believe it has to do with some intermediate state changes during image fetching.

**Comment by ahmedjamshed** [comment]
Can I improve that by returning false in shouldcomponentupdate until images are fully loaded? I can check that with fast image.

**Comment by brh55** [comment]
@ahmedjamshed The problem is bricks are resolved async so you'll probably run into issues there. Considering using redux to manage the async state, or migrate data.task to the new version which supports task cancellation and cancelled any unresolved bricks in component state.

**Comment by srameshr** [comment]
@brh55 Also support infinite loading

**Comment by sashabratchikov** [comment]
@brh55 

When I pass some navigation action as an `onPress` handler to bricks all my bricks suddenly disappear.

I think this is caused by `resolveBricks` called with an empty `bricks` array here:
https://github.com/brh55/react-native-masonry/blob/v0.5.0/components/Masonry.js#L102

In my case, the data is not changing after `onPress` so `brickDiff ` is an empty array (and `appendData` is `true`):
<img width="1189" alt="screen shot 2018-06-27 at 20 27 13" src="https://user-images.githubusercontent.com/10742104/41986886-a33ccbac-7a48-11e8-8110-eb114ff2213d.png">

so `resolveBricks` is called like this:
```
		if (appendedData) {
			const offSet = this.props.bricks.length;
			this.setState({
				_uniqueCount
			}, this.resolveBricks({...nextProps, bricks:[]}, offSet));
		}
```

**Comment by abhinav011085** [comment]
@brh55 I can not make it work with the latest create-react-native-app version. can you please try it with the current version and confirm?

Process i followed:-
1. npm install -g create-react-native-app
2. create-react-native-app AwesomeProject
3. cd AwesomeProject
4. npm install --save react-native-masonry
5. import Masonry from 'react-native-masonry';
6. <Masonry
  sorted // optional - Default: false
  columns={4} // optional - Default: 2
  bricks={[
    { uri: 'http://image1.jpg' },
    { uri: 'http://image2.jpg' },
    { uri: 'http://image3.jpg' }
  ]}
/>
7. npm start but getting error
...\node_modules\react-native\local-cli\cliEntry.js:30
import type {CommandT} from './commands';

SyntaxError: Unexpected token import

**Comment by lc3t35** [comment]
Hi, any plan to releasing this new version ?
